using System;
using System.Collections.Generic;

namespace PxSharp.ApiGen {
    public class OutputTarget {
        public string Directory = ".";
        public List<string> Files = new List<string>();

        public OutputFile CreateFile (string name) {
            Files.Add(name);
            OutputFile file = new OutputFile(Directory + "\\" + name);
            file.AppendLineFormat("// File generated by ApiGen on {0}", DateTime.Now);
            file.AppendLine();
            return file;
        }
    }
}
